---
title: "Pitch: Fourth Downs in College Football"
subtitle: |
  | JOUR 377
  | Winter Quarter, 2026
author: "Braedon Olsen"
pagetitle: "4th Down Story Pitch"
date: today

format:
  html:
    toc: true
    toc-location: left
    embed-resources: true
    link-external-newwindow: true
    code-fold: true

execute:
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin 
---

## Github Repository Link

[Github Repository Link](https://github.com/braedonolsen/down-4-data-story) for this data story.

## Pitch

Have you noticed teams going for it on fourth down more often? If so, your eyes are not deceiving you. With the rise in analytics used for in-game strategy and decision-making, college football teams are attempting fourth down conversions at unprecedented rates. Coaches who historically would have sent out the punt team on a 4th-and-2 are now scheming aggressive quarterback sneaks or trick plays to scrap for an extra set of downs. The numbers, whose hold on college football coaches is almost hypnotic, now dictate the strategy. For this story, I'd like to examine how the volume of fourth down conversion attempts in college football has shifted over the last 5-10 years. I would also aim to determine whether the success rate of these attempts has changed, and if so, what factors could be responsible.


## Data

My primary data source will be the online source [College Football Data](https://collegefootballdata.com/) (CFBD). CFBD offers free, relatively clean data on several aspects of college football via APIs and pre-built packs. For this story, I requested and received an API key from CFBD, which I will use to ensure I have the most up-to-date data possible. Luckily, since this year's college football season is complete, I will not have to worry about new data being added as I work on the project. However, if that were to be the case, all I would need to do to get the updated data would be to rerun the code that loads in the dataset.



## Sources

The hope for this story is that the data itself does the bulk of the storytelling. However, I did consult industry experts as well to get an inside look into the shifting fourth down strategy that has permeated college football. One such expert is Michael McRoberts, a Northwestern graduate who wrote a compilation of football strategies called the CAI Game Book. The book, used by over 100 college football programs, contains strategies for various aspects of football, including when to go for it on fourth down. I first learned about McRoberts after reading a piece that The Wall Street Journal wrote on him called “The Suburban Dad Who Calls Plays for 100 College Football Teams." As he is a Northwestern alum, I was able to contact him through the alumni database, and I completed an interview with him on February 20.


## Findings

From the analysis I conducted on my data, I came to the following key findings:

- Division I college football teams are attempting fourth downs more frequently than they have in the past. The attempt rate has increased from 19.8% to 26.4% between the 2016 and 2025 seasons.

- The spike in fourth down rate is especially notable for fourth-and-short situations. When teams have five or fewer yards to go, the rate at which they'll attempt a conversion on fourth down has increased from 34.7% to 46.3% over the last decade.

- Teams are relatively successful on fourth downs, especially with five or fewer yards to gain. On these short-yardage conversion attempts, teams generally convert around 60% of the time.

## Methodology

To arrive at my findings, I had to engage in several processing steps. These steps are outlined below.

The first line of action was obtaining my data from the CFBD API. I was able to easily download data, but it was more challenging to download multiple weeks or years at a time. I did not want to download data for each week individually for 10 years of data and manually join 100+ smaller datasets, so I created a function to allow me to instantly combine each week of each year from 2016 to 2025. Then, I filtered this massive dataset to only include observations on fourth down. I saved this dataset out to prevent myself from having to run the API code every time I wanted to come back and work on the project.

After I downloaded the initial dataset, I was able to continue processing the data to ensure its readiness for analysis. I was especially interested in my `playType` variable, as it contained valuable information on what kinds of plays could be considered "going for it" on a fourth down. I removed observations with play types such as "End of Game," "Kickoff," and "Timeout," as they did not contain data relevant to the question I was attempting to answer. I then created a variable called `go_for_it`, which indicated whether a team attempted a conversion or not on a particular fourth down. Finally, I added a variable called `success`, which used the information on distance to the first down marker and yards gained on the play to determine if a fourth down conversion attempt was successful or not.

The next step was analysis. I first looked at fourth down attempt rates. I used the `summarize()` function to get the fourth down rates grouped by season. Then, I created my visualization by extending that code, adding points for each season and a line to connect them for easier interpretation. I did the same thing for fourth down attempt rates in short yardage situations--the only new step was to filter the data to only include plays where the distance needed was five yards or less. I used similar strategies for fourth down success rate. The big difference for those figures was that I also needed to filter the data to only include observations where the team actually went for it, as I did not want to inadvertently include plays where a team punted or kicked a field goal. Finally, I saved out all these plots for easy retrieval.

To fact-check, I first reviewed all my code in R, line-by-line, making sure everything made sense and appeared correct. I then opened a blank R script, redownloaded my initial dataset, and attempted to replicate my original conclusions without looking at my original R scripts. When I was able to do this without issues, I felt more satisfied that my facts were indeed correct. However, just to make sure, I shared my work with a classmate and asked him to review my code for any errors. He told me that my work made sense to him and appeared to be reproducible, so I feel confident in my accuracy. For my non-data-driven facts, specifically the ones I obtained from Michael McRoberts, I reviewed my notes and my recording of the Zoom call I had with him, ensuring each quote and fact was accurate. After double-checking everything, I felt confident in my entire story.



## Flags

I am generally confident in my ability to produce a timely, engaging, and digestible story regarding fourth down strategy in college football. My data analysis showed the information is mostly complete and accurate, which is critical for the story to be of any use.

One issue I am grappling with is explaining the *why* regarding my topic. Through data wrangling and quantitative analysis, I am confident that I can illustrate the trend of teams going for it more often on fourth down. However, the data alone cannot explain why that is the case. In a perfect world, I would lean on outside sources and interviews to supply me with this information. I was able to speak with McRoberts, but I could not land an interview with a coach from the in-house perspective on this strategy. This makes sense, as they are generally required to be secretive about their playbooks, but it would have provided me with yet another valuable perspective to add to my story.






